server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: tit
          uri: http://localhost:8082/
          predicates:
            - Path=/tit/**

        - id: reservation-service
          uri: http://localhost:8081/
          predicates:
            - Path=/Reservation/**

        - id: security-service
          uri: http://localhost:8085/
          predicates:
            - Path=/**




management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include : gateway